### ISSUE TITLE
Most of the questions on this quiz are from other phases

### ISSUE THREAD

**Issue by bricknet1** [learn-co-curriculum/python-p4-quiz-building-apis#1]
### Canvas Link

https://learning.flatironschool.com/courses/6259/quizzes/45204

### Concern

The majority of the questions in this quiz don't apply to the content of the Building APIs modules in phase 4. As far as I can tell, only 1 question directly relates to the content of this section. A breakdown:
Question 1 - This question is fine.
Question 2 - I believe this language is Ruby, which is no longer being taught in the SE program.
Question 3 - This is about git and the terminal, which is fine but doesn't really directly relate to the content of this section.
Question 4 - This question is a direct copy of a question from the algorithms section from phase 2.
Question 5 - This question appears to be from phase 2 as well, regarding React.
Question 6 - I believe this language is Ruby, which is no longer being taught in the SE program.
Question 7 - This also appears to be from the algorithms section.

**Comment by pgill97** [comment]
This quiz was supposed to be deprecated but was accidentally included. It has been removed.
